# FILE: Dockerfile

FROM jeh/gcc:latest
WORKDIR /home/work
ENV DISPLAY :0
# CMD git clone https://github.com/xtforever/xtcw2.git; cd xtcw2 && git pull && make -j4 && cd test_scroll_list && make && ./cwri
